kind: DevOPSBatch
apiVersion: trainwithshubham.com/v1
metadata:
  name: enclave-2
spec:
  name: DevOPS - Zero to Hero Enclave 10
  duration: 4 months from 1st January 2026
  mode: Live Lectures
  platform: trainwithshubham.com
